name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]  # Убедитесь, что версия Python совпадает с используемой в проекте
    steps:
      - uses: actions/checkout@v2

      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Установка зависимостей
        run: |
          pip install poetry
          make install

      - name: Запуск линтера
        run: make lint

      - name: Сборка проекта
        run: make build

      - name: Публикация (тестовая)
        run: make publish

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Установка зависимостей
        run: |
          pip install poetry
          poetry install

      - name: Запуск Gunicorn
        run: make start
